### ISSUE TITLE
Misalignment with the profile picture in popout

### ISSUE THREAD

**Issue by tavvvvvvvvvvvvvv** [milbits/oldcord#16]
I feel like the profile picture in the popout is misaligned a little. Is it something else, or if it isn't, could you fix this?

![image](https://github.com/milbits/oldcord/assets/138950887/0de6afa7-b144-4206-8d26-3453aebed21f)

**Comment by milbits** [comment]
idk it looks fine to me

**Comment by tavvvvvvvvvvvvvv** [comment]
It looks fine for people/bots with tags but not so much for people with usernames

![image](https://github.com/milbits/oldcord/assets/138950887/8df59eb7-485d-4d6b-8b89-e50feb0440d4)

**Comment by milbits** [comment]
is this better, mr. perfectionist?
![image](https://github.com/milbits/oldcord/assets/51537072/f8674ac0-d487-48c2-a629-b5184b67d1c8)




![image](https://github.com/milbits/oldcord/assets/51537072/6611baf0-e553-4c5b-927c-960a085a6561)
my guy this is a nerd website

**Comment by tavvvvvvvvvvvvvv** [comment]
thats better but i wasn't calling you a nerd dude
