### ISSUE TITLE
If people have spotify/playstation connections, it'll show the spotify/playstation colors in the user popout

### ISSUE THREAD

**Issue by tavvvvvvvvvvvvvv** [milbits/oldcord#17]
![image](https://github.com/milbits/oldcord/assets/138950887/0baa4394-993b-463f-9bd7-e9e88e812382)
![image](https://github.com/milbits/oldcord/assets/138950887/4c4be870-30bb-4b34-aca6-0cbca2fbfd21)

**Comment by tavvvvvvvvvvvvvv** [comment]
never mind im retarded

**Comment by milbits** [comment]
😭💀
