### ISSUE TITLE
New icons are still present

### ISSUE THREAD

**Issue by ljcool2006** [milbits/oldcord#23]
Since today's Discord update, the icons now look kinda ugly.

![image](https://github.com/milbits/oldcord/assets/51834343/ed18c12d-9e51-4855-84b9-284a878b3889)

![image](https://github.com/milbits/oldcord/assets/51834343/bfb64b43-ad20-4c2a-a224-c0f39530c542)

**Comment by milbits** [comment]
also if you have the experiments tab you can set `Redesigned icons experiment` to control
![image](https://github.com/milbits/oldcord/assets/51537072/b9b3116a-374f-4d25-ac92-0f5736709ec7)

**Comment by andriemc** [comment]
> btw if you have the experiments tab you can set `Redesigned icons experiment` to control ![image](https://private-user-images.githubusercontent.com/51537072/288504799-b9b3116a-374f-4d25-ac92-0f5736709ec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDU4NTYsIm5iZiI6MTcwMjIwNTU1NiwicGF0aCI6Ii81MTUzNzA3Mi8yODg1MDQ3OTktYjliMzExNmEtMzc0Zi00ZDI1LWFjOTItMGY1NzM2NzA5ZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDEwNTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhY2QyMGM1NTBkMDJmOTA2MWYzMGZhMzVjNDQxOTUxZjBjNjFiNjg2YzgyZWIwMjBhYjI3MTRkNWRlZjQ3M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t1Xf_ipikbU6BJuUEOSkHlpvb9CEaDdRJOxjXw91IsY)

thanks!
