### ISSUE TITLE
Emoji icon not changing to the old one

### ISSUE THREAD

**Issue by ljcool2006** [milbits/oldcord#27]
Since probably today the emoji icon has been updated and the hover images look way different to the Twemoji ones.

![image](https://github.com/milbits/oldcord/assets/51834343/7e1500ed-7531-4991-a30c-aa759b734156)

![image](https://github.com/milbits/oldcord/assets/51834343/709daf28-4a52-4a4a-a73d-71bd95923944)

**Comment by milbits** [comment]
they're storing it in 2 seperate files now for some reason, + with more emojis
wont be super fun fixing that one

old:
![image](https://github.com/milbits/oldcord/assets/51537072/1b6da16b-e5d7-43c5-b17e-e23a601d67cd)
new:
![image](https://github.com/milbits/oldcord/assets/51537072/8c0f7f5a-046b-4fbd-8c0c-398279e64ba6)
![image](https://github.com/milbits/oldcord/assets/51537072/c35432e7-4d8a-46dc-b2e8-0517bbe29c63)

**Comment by ljcool2006** [comment]
the grayscale doesn't work
