### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by jozsaVilmos** [milbits/oldcord#73]
Hi, new bug this is with all plugins disabled.

![bug](https://github.com/user-attachments/assets/02e90736-53f6-4d2b-b062-e6bf29426d0c)

**Comment by milbits** [comment]
@KingGamingYT look you might've broken something!

**Comment by KingGamingYT** [comment]
huh

**Comment by KingGamingYT** [comment]
![image](https://github.com/user-attachments/assets/866c7163-7554-4aae-9a72-4a5b9e1bf6dc)
this is why I use `.userProfileModalInner_c69a7b`
![image](https://github.com/user-attachments/assets/5ee10a8f-fc98-4b9e-81e4-9f6f4e03a170)

**Comment by milbits** [comment]
but you added .colorprimary so technically its your fault :triumph:

**Comment by KingGamingYT** [comment]
> but you added .colorprimary so technically its your fault 😤

mf YOU added it, I got rid of it, and then added it back with the `:is(.grow_dd4f85)` pseudo when I realized it broke the message button :skull:

**Comment by milbits** [comment]
its called irony bitch
